apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-k8s-view-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-k8s-view
  template:
    metadata:
      labels:
        app: golang-k8s-view
    spec:
      containers:
      - name: golang-k8s-view
        image: andrewstewartelliott/golang-k8s-view:latest
        imagePullPolicy: IfNotPresent      # Prevents K8s from pulling online
        ports:
        - containerPort: 8080