apiVersion: v1
kind: ServiceAccount
metadata:
  name: golang-k8s-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: golang-k8s-view-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: golang-k8s-view
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-k8s-view-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-k8s-view
  template:
    metadata:
      labels:
        app: golang-k8s-view
    spec:
      serviceAccountName: golang-k8s-view
      containers:
      - name: golang-k8s-view
        image: andrewstewartelliott/golang-k8s-view:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: SERVICE_ACCOUNT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080